import {asset} from "../../../test/_helpers";

export const supportedAssetsAvax = [
    asset('AVAX'),
    asset('USDC'),
    asset('BTC'),
    asset('ETH'),
    asset('USDT'),
    asset('sAVAX'),
    asset('QI', 0),
    asset('PNG', 0),
    asset('PTP', 0),
    asset('PNG_AVAX_USDC_LP'),
    asset('PNG_AVAX_USDT_LP'),
    asset('PNG_AVAX_ETH_LP'),
    asset('TJ_AVAX_USDC_LP'),
    asset('TJ_AVAX_USDT_LP'),
    asset('TJ_AVAX_ETH_LP'),
    asset('TJ_AVAX_BTC_LP'),
    asset('TJ_AVAX_sAVAX_LP'),
    asset('YY_AAVE_AVAX'),
    asset('YY_PTP_sAVAX'),
    asset('YY_PNG_AVAX_USDC_LP'),
    asset('YY_PNG_AVAX_ETH_LP'),
    asset('YY_TJ_AVAX_sAVAX_LP'),
    asset('YY_TJ_AVAX_USDC_LP'),
    asset('YY_TJ_AVAX_ETH_LP'),
]